import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  root: { background: "#080C14" },
  sidebar: { background: "#0A0F1A" },
  logo: { display: "flex", alignItems: "center", gap: 10, padding: "0 20px 28px", borderBottom: "1px solid #1E293B" },
  logoIcon: { fontSize: 22, color: "#A78BFA" },
  logoText: { fontFamily: "'Sora'", fontWeight: 700, fontSize: 17, letterSpacing: "0.05em", color: "#F1F5F9" },
  navItems: {}, // Handled by CSS
  navBtn: { display: "flex", alignItems: "center", gap: 10, padding: "10px 14px", borderRadius: 8, border: "none", background: "transparent", color: "#64748B", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", fontWeight: 500, width: "100%", textAlign: "left", transition: "all 0.15s" },
  navBtnActive: { background: "#A78BFA18", color: "#A78BFA" },
  navIcon: { fontSize: 15, width: 18, textAlign: "center" },
  addBtn: { margin: "0 12px", padding: "11px 16px", background: "linear-gradient(135deg, #A78BFA, #818CF8)", border: "none", borderRadius: 10, color: "#fff", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", fontWeight: 600, display: "flex", alignItems: "center", justifyContent: "center", transition: "opacity 0.15s" },
  sidebarFooter: {}, // Handled by CSS
  footerStat: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  footerLabel: { fontSize: 11, color: "#475569", letterSpacing: "0.05em", textTransform: "uppercase" },
  footerValue: { fontSize: 14, fontFamily: "'DM Mono'", fontWeight: 500, color: "#A78BFA" },
  main: { flex: 1, overflow: "auto", position: "relative" },
  toast: { position: "fixed", top: 20, right: 20, padding: "12px 20px", borderRadius: 10, color: "white", fontSize: 13, fontWeight: 500, zIndex: 1000, boxShadow: "0 8px 32px rgba(0,0,0,0.4)", animation: "none" },
  page: {}, // Handled by CSS
  pageHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 28 },
  pageTitle: { fontSize: 26, fontWeight: 700, color: "#F1F5F9", letterSpacing: "-0.02em" },
  pageSubtitle: { fontSize: 13, color: "#64748B", marginTop: 4 },
  primaryBtn: { padding: "10px 20px", background: "linear-gradient(135deg, #A78BFA, #818CF8)", border: "none", borderRadius: 8, color: "#fff", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", fontWeight: 600 },
  ghostBtn: { padding: "10px 20px", background: "transparent", border: "1px solid #334155", borderRadius: 8, color: "#94A3B8", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", fontWeight: 500 },
  statsRow: {}, // Handled by CSS
  statCard: { background: "#0D1420", border: "1px solid #1E293B", borderRadius: 14, padding: "18px 20px", position: "relative", overflow: "hidden" },
  statAccent: { position: "absolute", top: 0, left: 0, right: 0, height: 2, borderRadius: "14px 14px 0 0" },
  statLabel: { fontSize: 11, color: "#64748B", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 },
  statValue: { fontSize: 24, fontFamily: "'DM Mono'", fontWeight: 500, letterSpacing: "-0.02em", marginBottom: 4 },
  statSub: { fontSize: 11, color: "#475569" },
  twoCol: {}, // Handled by CSS
  card: { background: "#0D1420", border: "1px solid #1E293B", borderRadius: 14, padding: "22px 24px", marginBottom: 16 },
  cardTitle: { fontSize: 14, fontWeight: 600, color: "#94A3B8", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 16 },
  catRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 12 },
  catLeft: { display: "flex", alignItems: "center", gap: 8, width: 150 },
  catDot: { width: 26, height: 26, borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, color: "#fff", fontWeight: 600, flexShrink: 0 },
  catName: { fontSize: 13, color: "#CBD5E1" },
  catBarWrap: { flex: 1, height: 5, background: "#1E293B", borderRadius: 10, overflow: "hidden" },
  catBar: { height: "100%", borderRadius: 10, transition: "width 0.5s ease" },
  catAmt: { width: 64, textAlign: "right", fontSize: 13, fontFamily: "'DM Mono'", color: "#94A3B8" },
  upcomingRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0", borderBottom: "1px solid #1E293B", cursor: "pointer" },
  upcomingInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 2 },
  upcomingName: { fontSize: 14, fontWeight: 500, color: "#E2E8F0" },
  upcomingDate: { fontSize: 11, color: "#64748B", fontFamily: "'DM Mono'" },
  upcomingAmt: { fontSize: 12, fontFamily: "'DM Mono'", color: "#94A3B8", marginTop: 3 },
  badge: { display: "inline-block", padding: "2px 8px", borderRadius: 20, fontSize: 11, fontWeight: 600, fontFamily: "'DM Mono'" },
  subIcon: { width: 36, height: 36, borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15, color: "#fff", fontWeight: 700, flexShrink: 0 },
  subIconLg: { width: 56, height: 56, borderRadius: 14, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, color: "#fff", fontWeight: 700, flexShrink: 0 },
  presetGrid: { display: "flex", flexWrap: "wrap", gap: 8 },
  presetBtn: { display: "flex", alignItems: "center", gap: 8, padding: "8px 14px", background: "#141E30", border: "1px solid #1E293B", borderRadius: 8, color: "#CBD5E1", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", transition: "border-color 0.15s" },
  presetIcon: { width: 24, height: 24, borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, color: "#fff", fontWeight: 700, flexShrink: 0 },
  presetName: { fontSize: 12 },
  filtersRow: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap", alignItems: "center" },
  searchInput: { padding: "9px 14px", background: "#0D1420", border: "1px solid #1E293B", borderRadius: 8, color: "#E2E8F0", fontSize: 13, fontFamily: "'Sora'", outline: "none", flex: "1 1 160px" },
  select: { padding: "9px 14px", background: "#0D1420", border: "1px solid #1E293B", borderRadius: 8, color: "#E2E8F0", fontSize: 13, fontFamily: "'Sora'", outline: "none", cursor: "pointer" },
  toggleLabel: { fontSize: 13, color: "#64748B", cursor: "pointer", display: "flex", alignItems: "center" },
  subList: { display: "flex", flexDirection: "column", gap: 8 },
  subRow: { display: "flex", alignItems: "center", gap: 14, background: "#0D1420", border: "1px solid #1E293B", borderRadius: 12, padding: "14px 18px", transition: "background 0.15s", cursor: "default" },
  subInfo: { flex: 1 },
  subName: { fontSize: 14, fontWeight: 600, color: "#E2E8F0", marginBottom: 5 },
  subMeta: { display: "flex", alignItems: "center", gap: 6 },
  catChip: { fontSize: 10, fontWeight: 600, padding: "2px 7px", borderRadius: 20, textTransform: "uppercase", letterSpacing: "0.05em" },
  metaSep: { color: "#334155" },
  metaText: { fontSize: 11, color: "#64748B", fontFamily: "'DM Mono'" },
  subRight: { textAlign: "right", minWidth: 80 },
  subAmt: { fontSize: 15, fontFamily: "'DM Mono'", fontWeight: 500, color: "#E2E8F0" },
  subCycle: { fontSize: 11, color: "#64748B" },
  subMonthly: { fontSize: 11, color: "#64748B", fontFamily: "'DM Mono'", marginTop: 2 },
  subActions: { display: "flex", gap: 4 },
  iconBtn: { padding: "6px 9px", background: "#141E30", border: "1px solid #1E293B", borderRadius: 7, color: "#64748B", cursor: "pointer", fontSize: 13, fontFamily: "'Sora'", transition: "color 0.15s, border-color 0.15s" },
  emptyState: { display: "flex", flexDirection: "column", alignItems: "center", gap: 16, padding: "60px 0", color: "#475569" },
  emptyIcon: { fontSize: 48, color: "#1E293B" },
  emptyText: { fontSize: 13, color: "#475569", textAlign: "center", padding: "20px 0" },
  formPreview: { display: "flex", gap: 16, alignItems: "flex-start", marginBottom: 20, padding: "16px", background: "#080C14", borderRadius: 10 },
  formRow: { marginBottom: 16 },
  formGrid: {}, // Handled by CSS
  label: { display: "block", fontSize: 11, color: "#64748B", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 6 },
  input: { width: "100%", padding: "10px 14px", background: "#080C14", border: "1px solid #1E293B", borderRadius: 8, color: "#E2E8F0", fontSize: 13, fontFamily: "'Sora'", outline: "none" },
  calcPreview: { background: "#A78BFA18", border: "1px solid #A78BFA33", borderRadius: 8, padding: "10px 14px", fontSize: 13, color: "#A78BFA", marginBottom: 16, fontFamily: "'DM Mono'" },
  formActions: { display: "flex", gap: 10, justifyContent: "flex-end" },
};
